---
title: EDWINA'S FIRST BLOG
date: 2019-02-20
---
author: Edwina
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my first blog.

# social links
twitter_username: twitter.com/edwinamuir
github_username:  github.com/edgmuir

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
